#!/usr/bin/env python

import rospy

from fri_burger_bot.burger_bot import BurgerBot



if __name__ == '__main__':

    rospy.init_node("BurgerBot")

    # rospy.spin()
    bot = BurgerBot()
    bot.start()
    bot.join()
